regmachine via Rfsfun
volodeyka/event-struct pull request #31
Opened 2020-12-06 10:41 UTC by volodeyka

2020-12-06 11:46 UTC, anton-trunov commented on transitionsystem.v
> +                        ((lab add_write) << add_lb);
Is it feasible to remove spec duplication between `add_write_consist` and `wr`? It seems this is generalizable. This might improve proofs.

2020-12-06 11:46 UTC, anton-trunov commented on transitionsystem.v
> +(*         add_label_of_Nread == takes non-read label and precessor and       *)
"precessor" -> "predecessor"?

2020-12-06 11:46 UTC, anton-trunov commented on transitionsystem.v
> +  ((fresh == fresh) && (~~ is_read l)) || ((lab fresh) << l).
`fresh == fresh` looks weird... If you really need this then let's demote it from `Lemma` to `Fact` at least. It does not seem like a generally reusable lemma to me.

2020-12-06 11:46 UTC, anton-trunov commented on regmachine.v
> +(*             instr == regmachine instructions                               *)
Why this indentation? :)

2020-12-06 11:46 UTC, anton-trunov commented on regmachine.v
> +Context {val : inhType} {disp} {E : identType disp}.
Ah, good old name clash with `eqtype`'s `val` :) Can we fix this?

2020-12-06 13:23 UTC, volodeyka commented on transitionsystem.v
> +                        ((lab add_write) << add_lb);
Hm, yes it’s seems like I’ve some idea. I’ll try it)

2020-12-06 13:29 UTC, volodeyka commented on transitionsystem.v
> +  ((fresh == fresh) && (~~ is_read l)) || ((lab fresh) << l).
Unfortunately, we need to give this lemma to Add constructor. I don’t know if it is better to build this term by hands... So renaming seems like the best idea for me

2020-12-06 13:31 UTC, volodeyka commented on regmachine.v
> +(*             instr == regmachine instructions                               *)
🤷🏻‍♂️

2020-12-06 13:34 UTC, volodeyka commented on regmachine.v
> +Context {val : inhType} {disp} {E : identType disp}.
Oh, yes... maybe “value” but it other names contain only three letters (loc, var...). @eupp ?

2020-12-07 08:56 UTC, volodeyka commented on regmachine.v
> +(*             instr == regmachine instructions                               *)
Stop. I thought that comment should be somewhere in the middle... Should I write 
```Coq
(* This file contains definition of:                                          *)
(* instr == regmachine instructions                                      *)
...
```

2020-12-07 09:15 UTC, anton-trunov commented on regmachine.v
> +(*             instr == regmachine instructions                               *)
The Mathcomp format is to align `==` vertically. So the indentation is not constant and depends on the lengths of the identifiers in a group (and their parameters).

2020-12-07 17:33 UTC, eupp requested changes

2020-12-07 17:33 UTC, eupp commented on regmachine.v
> +      Add pr_mem (@ws_mem x w) (ws_wpred w))),
I'm confused at this point. 
How the label that we want to add is inferred here? 
Is it inferred indirectly through the `ws_wpred` type? 
If so, then it is a very bad idea. I spent like 15 mins trying to understand this little piece of code. And I am the person who has some intuition behind what is happening here. Imagine a completely random person who has no idea about event structures, memory models, etc. 

Implicit arguments are the devil's weapon. You should never abuse it.

2020-12-07 17:33 UTC, eupp commented on transitionsystem.v
> +  ((fresh == fresh) && (~~ is_read l)) || ((lab fresh) << l).
Besides the fact, that it looks weird, you also use `Lemma` and `Qed` here, which makes the term non-opaque, I guess? Wouldn't it hurt extraction?

2020-12-07 17:33 UTC, eupp commented on regmachine.v
> +    [seq (Conf x.1 [fsfun c with fresh |-> cont_st x.2]) |
Numbered projections, like `.1` or `.2`, are rarely used in any programming language. 
Generally, a better approach is to use `let` to destruct the pair into components or define the record with named fields.

2020-12-07 17:33 UTC, eupp commented on regmachine.v
> +  else [:: Conf (evstr c) [fsfun c with pr |-> cont_st inh]].
What about `if-then-else` indentation?
I remember we had 50/50 in the vote :) 
But here, I guess, the following indentation would look nicer:
```
if ... then 
   ...
else 
   ...
```

2020-12-07 17:33 UTC, eupp commented on transitionsystem.v
> +Lemma lab_fresh: lab fresh = ThreadEnd.
Sometimes you don't add space before the `:`, sometimes you do. We need to be consistent. 
I think it's better to always surround `:` with spaces in lemmas. 
`Lemma lab_fresh : lab fresh = ThreadEnd.`

2020-12-07 17:33 UTC, eupp commented on regmachine.v
> +  seq (sig_subType (fun y => (wpred x y) && (y \in dom))) :=
Can we leave the type on the same line as the `Definition`? 
I guess in general it is better to avoid newlines unless the definition/lemma has a lot of arguments.

2020-12-07 17:33 UTC, eupp commented on regmachine.v
> +  seq (sig_subType (fun y => (wpred x y) && (y \in dom))) :=
Wouldn't it be better to just use the notation `{ x | P }` for sigma types here (instead of `sig_subType`)?
@anton-trunov

2020-12-07 18:10 UTC, volodeyka commented on regmachine.v
> +  pmap insub dom.
All these steps can be done just using `filter` because we have inside the `exec_event_structure` sequence of its events. But unfortunately, after `filter` we are losing information that our filtered elements satisfy filtration-predicate... It is difficult to explain offline, I think it would be better to discuss it at the meeting

2020-12-07 18:11 UTC, volodeyka commented on regmachine.v
> +      Add pr_mem (@ws_mem x w) (ws_wpred w))),
Oh, sorry for that

2020-12-07 18:14 UTC, volodeyka commented on regmachine.v
> +  seq (sig_subType (fun y => (wpred x y) && (y \in dom))) :=
> Can we leave the type on the same line as the `Definition`?
> I guess in general it is better to avoid newlines unless the definition/lemma has a lot of arguments.

but line with all this stuff is going to be 85 symbols long(

2020-12-07 18:15 UTC, volodeyka commented on regmachine.v
> +  seq (sig_subType (fun y => (wpred x y) && (y \in dom))) :=
> Wouldn't it be better to just use the notation `{ x | P }` for sigma types here (instead of `sig_subType`)?
> @anton-trunov

Oh, I agree)

2020-12-08 08:56 UTC, volodeyka commented on regmachine.v
> +Notation fresh := (fresh_seq dom).
`fresh_id` maybe?

2020-12-08 09:37 UTC, volodeyka commented on regmachine.v
> +Context {val : inhType} {disp} {E : identType disp}.
It is simpler just to get rid of `subType`

2020-12-09 11:37 UTC, eupp approved these changes

2020-12-09 11:37 UTC, eupp commented on regmachine.v
> +                     fun _ => {| ip     := i.+1;
indentation inconsistency (either indent `ip := ...` in all branches or do not indent it)

2020-12-09 11:37 UTC, eupp commented on regmachine.v
> +   (lloc (lab w) == some x) && (is_write (lab w)).
:+1:

2020-12-09 16:13 UTC, merged