Refactoring of relations.v
volodeyka/event-struct pull request #34
Opened 2020-12-07 18:52 UTC by dmitromikh

2020-12-09 11:28 UTC, eupp requested changes

2020-12-09 11:28 UTC, eupp commented on relations.v
> +Notation base := (@tn1_step T (sfrel f\eq) _).
How these notations are used?

2020-12-09 11:28 UTC, eupp commented on relations.v
> +Lemma trans_refl_trans a b  {R : rel T}:
By analogy to `clos_r_clos_rt` let's name it `clos_t_clos_rt`. 
Also, I think it's better to have `R` as the first argument.

2020-12-09 11:28 UTC, eupp commented on relations.v
> +Proof. move=> a. exact: mem_head. Qed.
Put it near to `rt_closure_trans`

2020-12-09 11:28 UTC, eupp commented on relations.v
> +Lemma refl_trans_refl_rt a b :
Looks like this one is a very technical lemma. Is it really needed outside `rt_closureP`? 
If not, I would just put it back into `rt_closureP` proof.

2020-12-09 11:28 UTC, eupp commented on relations.v
> +Lemma refl_eq_neq a b {R : relation T} :
I think this kind of lemmas is named with the suffix `E` in ssreflect? @anton-trunov 
If so, I would propose to rename it into `clos_reflE` and also proof the other direction, i.e. to have 
`clos_refl T R a b <-> (a == b) \/ R a b`

2020-12-09 16:36 UTC, volodeyka commented on relations.v
> +Lemma rt_closure_refl : reflexive rt_closure.
@anton-trunov said that reflexivity should be formulated explicitly (because otherwise, reduction works bad).

2020-12-09 16:38 UTC, volodeyka commented
Can we prove here antisymmetry of closed relation?

2020-12-09 18:51 UTC, anton-trunov commented on relations.v
> +Lemma rt_closure_refl : reflexive rt_closure.
Not really reduction. It's the `auto` tactic and alike. Those do not run reduction, so they won't be able to see that `R x x` can be solved with `reflexive R`, so `//` is not going to work on these trivial goals.

2020-12-09 18:55 UTC, anton-trunov commented on relations.v
> +Lemma refl_trans_refl_rt a b :
I would say `(a == b) \/ R a b` is a mix of boolean and propositional statements. It seems that if it's needed at all it should either be `(a = b) \/ R a b` or `(a == b) || R a b`.

2020-12-09 18:56 UTC, anton-trunov commented on relations.v
> +Lemma refl_trans_refl_rt a b :
Sorry, this comment was intended for `refl_eq_neq` lemma.

2020-12-09 18:59 UTC, anton-trunov commented on relations.v
> +Lemma refl_eq_neq a b {R : relation T} :
The suffix `E`  is for *elimination*, e.g. `negbFE : ~~ b = false -> b`, which means negation elimination related to boolean false (`F`).

2020-12-09 19:29 UTC, anton-trunov commented
The fact that this PR unfold things like `filter_neq` and `filter_lt` *a lot* tells us that either these definitions are not covered with enough lemmas or that these definitions are spurious and not well justified. (Rant aside: sorry, but I especially dislike the notation for `filter_neq`.)

2020-12-10 08:43 UTC, eupp commented on relations.v
> +Lemma refl_eq_neq a b {R : relation T} :
> The suffix `E` is for _elimination_, e.g. `negbFE : ~~ b = false -> b`, which means negation elimination related to boolean false (`F`).

So then want name for this lemma we should pick ?)

2020-12-10 08:49 UTC, eupp commented
> The fact that this PR unfold things like `filter_neq` and `filter_lt` _a lot_ tells us that either these definitions are not covered with enough lemmas or that these definitions are spurious and not well justified. (Rant aside: sorry, but I especially dislike the notation for `filter_neq`.)

I generally agree. The whole `filter_neq` business looks hacky. But we need it if we have a non-strict descend axiom:

```Coq
Hypothesis descend : forall x n, x \in f n -> x <= n.
```

I have a feeling that with the strict version the theory and proofs would look nicer. 
But we have added the non-strict version in order to also cover the case (in future) of regular total functions of type `f : A -> A`. 
Here we cannot assume that function is strictly-decreasing w.r.t. to well-founded order. 
In this case we use the loop trick and map the "terminal" element to itself. 
But then, we need to handle this "looping", that is exactly what `filter_neq` is responsible for.

2020-12-10 13:01 UTC, anton-trunov commented on relations.v
> +Lemma refl_eq_neq a b {R : relation T} :
Oh, yes, you are right. `clos_reflE` is a fine name in this case. Sorry, the UI gets confusing with a lot of comments in-place.

2020-12-10 13:04 UTC, anton-trunov commented
Ah, I see! I this case I'd suggest to rename `filter_neq` semantically then (`non_looping` or `strict` or something like that). And a small theory of it should be developed so that there would be no need to unfold it.

2020-12-10 14:27 UTC, dmitromikh commented on relations.v
> +Definition hack n (g : forall x : T, x < n -> seq T) :=
I agree, will it be better to call it `s_up_set_aux`?

2020-12-10 14:33 UTC, dmitromikh commented on relations.v
> +Notation base := (@tn1_step T (sfrel f\eq) _).
They were used in the proof of the `t_closureP` lemma, but they can be easily removed.

2020-12-10 14:35 UTC, dmitromikh commented on relations.v
> +Lemma refl_t_rt a b :
Okay.

2020-12-10 14:40 UTC, dmitromikh commented on relations.v
>  Lemma t_closureP a b :
Okay.

2020-12-10 14:48 UTC, dmitromikh commented on relations.v
> +Lemma clos_trans_lt a b : clos_trans_n1 T (sfrel f\eq) a b -> a < b.
Okay.

2020-12-10 14:50 UTC, dmitromikh commented on relations.v
> +Lemma trans_refl_trans a b  {R : rel T}:
Okay.

2020-12-10 14:54 UTC, dmitromikh commented on relations.v
> +Proof. move=> a. exact: mem_head. Qed.
It is here because it is used in the proof of `rt_closureP` which, in turn, is used in the proof of `rt_closure_trans`.

2020-12-10 15:13 UTC, dmitromikh commented on relations.v
> +Lemma refl_trans_refl_rt a b :
Yes, it is technical, so I'll move it into the proof of `refl_trans_refl_rt`.

2020-12-10 15:14 UTC, dmitromikh commented on relations.v
> +Lemma refl_eq_neq a b {R : relation T} :
Well, now we don't need its name :)

2020-12-10 15:14 UTC, dmitromikh commented on relations.v
> +Lemma rt_closure_refl : reflexive rt_closure.
Okay.

2020-12-11 08:22 UTC, eupp commented on relations.v
> +Definition hack n (g : forall x : T, x < n -> seq T) :=
> I agree, will it be better to call it `s_up_set_aux`?

For now, this name should work. 
In a while I'm still think about a better name for `s_up_set`.

2020-12-11 08:22 UTC, eupp commented on relations.v
> +Notation base := (@tn1_step T (sfrel f\eq) _).
> They were used in the proof of the `t_closureP` lemma, but they can be easily removed.

If it's not crucial, I would remove them.

2020-12-11 08:23 UTC, eupp commented on relations.v
> +Proof. move=> a. exact: mem_head. Qed.
I see. Okay then.

2020-12-11 08:24 UTC, eupp commented on relations.v
> +Lemma refl_eq_neq a b {R : relation T} :
Still, it might be a useful lemma. We can leave it (and, perhaps, put it into `utilities.v`)

2020-12-11 08:32 UTC, eupp requested changes

2020-12-11 08:32 UTC, eupp commented on relations.v
> +  reflect (clos_refl_trans_n1 T (sfrel f) a b) (rt_closure a b).
I would propose to do with `rt_closureP` the same as we did with `t_closureP`, i.e. to have two versions for `clos_refl_trans_n1` and `clos_refl_trans`.

2020-12-11 09:32 UTC, dmitromikh commented on relations.v
> +Proof. move=> a. exact: mem_head. Qed.
Yeah, you're right. It's my fault.

2020-12-11 11:39 UTC, dmitromikh commented on relations.v
> +  reflect (clos_refl_trans_n1 T (sfrel f) a b) (rt_closure a b).
Okay.

2020-12-11 11:48 UTC, eupp commented on relations.v
> +Proof. move=> a. exact: mem_head. Qed.
> Yeah, you're right. It's my fault.

It's fine :)
So could you please then move it near to `rt_closure_trans` (before it).

2020-12-11 12:07 UTC, eupp commented
I would propose to postpone the `filter_neq` stuff and later make another PR targeting its refactoring. 
So that we can merge the current piece of work into master.

2020-12-11 12:07 UTC, eupp approved these changes

2020-12-11 18:14 UTC, merged