refactor: remove rfsfun and refactor proofs
volodeyka/event-struct pull request #56
Opened 2021-01-07 21:18 UTC by anton-trunov

I realize this is a pretty big PR to review (sorry about that). It is the result of my attempts to make sense of `rfsfun` (which I unfortunately failed).
Instead I pursued the other direction and removed `rfsfun` altogether. Hence, it's debatable whether this PR needs to get merged but I believe the result is conceptually simpler code (which still can be streamlined more basing on this PR).

To ensure the `lab`, `fpred` and `frf` functions are defined over the same domain I merged those three functions into one function returning a triple.

I added some new lemmas and moved around a few existing lemmas and definition (e.g. `lloc` and `is_write` are in `eventstructure.v` now)  and also renamed some things.

2021-01-08 17:07 UTC, eupp requested changes

2021-01-08 17:07 UTC, eupp commented on eventstructure.v
> +Definition is_write l := if l is Write _ _ then true else false.
Good that you've moved it here, where it belongs :+1:

2021-01-08 17:07 UTC, eupp commented on eventstructure.v
> +  frf e      := (lprf e).2;    (* frf is 3d projection *)
These projections do not look nice :(
Maybe instead of tuple, we'll define the `Record` with named fields?

2021-01-08 17:07 UTC, eupp commented on eventstructure.v
> +                 (((w == r) && ~~ is_read (lab r)) || ((lab w) << (lab r)));
We can split these two properties into two separate axioms

2021-01-08 17:07 UTC, eupp commented on eventstructure.v
> +Proof. by []. Qed.
Also, related to the problem with projections, these lemmas a bit frustrating too

2021-01-08 17:07 UTC, eupp commented on eventstructure.v
> +Lemma icfxx x : icf x x = false.
A better name would be `icf_irrefl` (irreflexive)

2021-01-08 17:07 UTC, eupp commented on eventstructure.v
>  Notation domain := (dom es).
Let the notation be the same as the definition, i.e. just `dom` instead of `domain`. 
Having the two names for the same thing is a bit confusing.

2021-01-08 17:09 UTC, eupp commented
@anton-trunov thanks for this PR. 

I liked the idea to enforce the same-domain constraint through the tuple-valued function. 
However, the use of (unnamed) projections worries me a bit. 
How can we get around it? 
Perhaps we can use a `Record` with meaningful names for fields (and also specify the types of the components, for clarity).

2021-01-10 15:19 UTC, anton-trunov commented on eventstructure.v
> +                 (((w == r) && ~~ is_read (lab r)) || ((lab w) << (lab r)));
This is how it was formulated in the first place. How about we create an issue for it and handle in a separate PR? (I'm happy to be the assignee for the issue).

2021-01-10 16:58 UTC, anton-trunov commented on eventstructure.v
> +Lemma icfxx x : icf x x = false.
Mathcomp uses both `_irrefl` and `_irreflexive` suffixes and `xx` (without the underscore) is consistently used to both mean reflexivity and irreflexivity lemmas (e.g. there is `eqxx`, `lexx`, `ltxx` lemmas in `eqtype` and `order` libraries). I'd suggest to add `icf_irrefl` as an alias for `icfxx` (which is easier to use in rewrite chains) which is also something Mathcomp uses.

2021-01-10 17:01 UTC, anton-trunov commented on eventstructure.v
>  Notation domain := (dom es).
Agreed and fixed :)

2021-01-10 17:02 UTC, anton-trunov commented on eventstructure.v
> +Lemma rf_thdend w : w << ThreadEnd = false.
Done.

2021-01-10 17:04 UTC, anton-trunov commented
> I liked the idea to enforce the same-domain constraint through the tuple-valued function.
> However, the use of (unnamed) projections worries me a bit.
> How can we get around it?

Thanks for the review suggestion! Ok, let me make one more pass on the projections issue which admittedly I didn't want to invest much time into before having a general consensus on the rfsfun removal. I'll get back to this issue next week.

2021-01-12 08:11 UTC, eupp commented on eventstructure.v
> +                 (((w == r) && ~~ is_read (lab r)) || ((lab w) << (lab r)));
> This is how it was formulated in the first place. How about we create an issue for it and handle in a separate PR? (I'm happy to be the assignee for the issue).

Ok, I see. 
I think it'll take more time to open an issue for this minor problem than just fixing it :)
I'll do that (perhaps after we'll merge this PR, so as to avoid unnecessary conflicts).

2021-01-12 08:16 UTC, anton-trunov commented on eventstructure.v
> +                 (((w == r) && ~~ is_read (lab r)) || ((lab w) << (lab r)));
Sure, I was thinking it might force us to refactor quite a few proofs but I'm happy to be wrong here :)

2021-02-19 07:37 UTC, eupp commented on eventstructure.v
> +Lemma prod_of_lprfK : cancel prod_of_lprf lprf_of_prod. Proof. by case. Qed.
Let's put `Proof/Qed` on the next line.

```suggestion
Lemma prod_of_lprfK : cancel prod_of_lprf lprf_of_prod. 
Proof. by case. Qed.
```

2021-02-19 07:38 UTC, eupp approved these changes

2021-02-19 11:10 UTC, merged

2021-02-19 11:11 UTC, anton-trunov commented
@eupp Thanks for all the suggestions!