Reflexive-transitive closure for well-founded relations
volodeyka/event-struct pull request #7
Opened 2020-10-06 21:40 UTC by dmitromikh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/volodeyka/event-struct/7)

2020-11-23 15:43 UTC, eupp requested changes

2020-11-23 15:43 UTC, eupp commented on relations.v
> +          [seq x <- f n | x != n]
First, use `let`-binding in order to avoid duplicate evaluation of `f n`. 
Second, I think, it is better to left the lambda on the same line as `map`. 
Also, it's sometimes convinient to have a version of the `map` that takes the function as second argument. 
Therefore, I would propose the following:

```Coq
Equations(noind) t_closure (n : T) : seq T by wf n (<%O : rel T) :=
  t_closure n := 
    let ys := [ seq y <- f n | y != n ] in 
    let ps := flatten (map^~ ys (fun x => 
      if x \in ys =P true is ReflectT pf then
        t_closure x
      else 
        [::]
    )) in
    ys ++ ps.
```

2020-11-23 15:43 UTC, eupp commented on relations.v
> +  exact: filter_lt.
one-line proof again :)

2020-11-23 15:43 UTC, eupp commented on utilities.v
> +   (at level 0, only parsing) : ssripat_scope.
Do we still need this?
I remember there was some discussion that newer version of ssreflect has similar tactics out of the box

2020-11-23 15:43 UTC, eupp commented on relations.v
> +  done.
After minor cleanup:
```Coq
  rewrite /rel_of_closure.
  move: b a. apply: wf_ind => b IH a.
  rewrite /t_closure /Subterm.FixWf Fix_eq; last by apply: ext_t_closure.
  rewrite {1}/t_closure_functional mem_cat => /orP [/filter_lt //|].
  case/flatten_mapP=> x /filter_lt xinf.
  case: eqP => //. move=> /filter_lt /IH /apply ax. 
  by apply: lt_trans; first apply: ax.
```

2020-11-23 15:43 UTC, eupp commented on relations.v
> +  move=> _. apply/IHd=> //=. exact: filter_lt.
After a minor cleanup.

```Coq
  rewrite /rel_of_closure.
  move: b a. apply: wf_ind=> b IH a.
  apply /(iffP idP).
  { rewrite /t_closure /Subterm.FixWf Fix_eq; last by apply: ext_t_closure.
    rewrite {1}/t_closure_functional mem_cat => /orP [].
    { by constructor. }
    case/flatten_mapP=> x xinf. case: eqP=> //=.
    move=> /filter_lt /IH /apply H. 
    apply /clos_trans_tn1 /t_trans; first last.
    { constructor. apply: xinf. }
    apply /clos_tn1_trans. exact: H. }
  move=> ctab. move: ctab IH. case.
  { rewrite /rel_of_fun /= => c afc IH.
    rewrite /t_closure /Subterm.FixWf Fix_eq; last by apply: ext_t_closure.
    by rewrite {1}/t_closure_functional mem_cat afc. }
  move=> c d. rewrite /rel_of_fun /= => cfd ctac IHd.
  rewrite /t_closure /Subterm.FixWf Fix_eq; last by apply: ext_t_closure.
  rewrite {1}/t_closure_functional mem_cat. apply/orP.
  right. apply/flatten_mapP. exists c=> //=. case: eqP=> //=.
  move=> _. apply/IHd=> //=. exact: filter_lt.
```

2020-11-24 10:13 UTC, anton-trunov commented on relations.v
> +From event_struct Require Import utilities wftype.
That's a great suggestion! I'd also add to keep only the used imports and get rid of the rest.
This gives a clearer big picture and keeps search results at bay :)

2020-11-25 16:11 UTC, dmitromikh commented on wftype.v
> +End  WfInduction.
An instance of Equations.WellFounded is added here.

2020-11-25 16:23 UTC, dmitromikh commented on relations.v
> +  [rel a b | a \in [seq x <- f b | x != b]].
I agree, let's use `sfrel`.

2020-11-25 16:38 UTC, dmitromikh commented on utilities.v
> +   (at level 0, only parsing) : ssripat_scope.
Yeah, we do not need this anymore.

2020-11-27 09:17 UTC, eupp commented
I did some stylistic changes. 

1. Now, `sfrel` by default does not remove anything from the list that `f` returns. 
2. I've added a notation for `filter_neq`
3. I've renamed some definitions. The function that computes the list of predecessors is called `s_up_set` for a strict upward set. 
I've borrowed terminology from [order theory](https://en.wikipedia.org/wiki/Upper_set). The intuition is the following. Given function `f` we can view it as a relation `R`. Then, our function, given some element `x`, computes the set of accessible elements of `x`, that is a set `{ y | x R^+ y }`. That is an upper (upward) set of `x`. 
Then the computational transitive and reflexive-transitive closures are named `t_closure` and `rt_closure` (without the `_rel` suffix as was before).

@dmitromikh @volodeyka have a look. 
If you have any objections, please share it.

2020-11-30 14:15 UTC, merged