Generalize relations from seq to monad
volodeyka/event-struct pull request #79
Opened 2021-04-16 21:21 UTC by dmitromikh

2021-04-22 08:18 UTC, eupp requested changes

2021-04-22 08:18 UTC, eupp commented on monad.v
> +Notation "f ≈≈> g" := (monmorph f g) (at level 51) : monae_scope.
I've already changed this thing in a previous PR :) 
My idea was that we do not export `Syntax` module by default, so the `≈>` notation is not available by default. 
The user can export the suitable `Syntax` module and use it locally to denote the morphism between certain class of monads. 
E.g. if the use is working with usual monads it does the following
```
Import MonadMorphism.Syntax.
```

If it is working with non-det monads it does:
```
Import NDMonadMorphism.Syntax.
```

This way we do not need to invent a new notation for each class of monad morphisms. 

Also, I propose to use `≈>` instead of `≈≈>`, by analogy with `~>` notation for natural transformations from `monae`.

2021-04-22 08:18 UTC, eupp commented on relations.v
> +  s >>= (fun a => if p a then Ret a else Fail).
Let's move theory of `mfilter` into `monad.v`

2021-04-22 08:18 UTC, eupp commented on relations.v
> +Lemma mem_ret_eq (x y : T) :
perhaps `mem_ret_in` would be a better name?

2021-04-22 08:18 UTC, eupp commented on relations.v
> +  rewrite /ModelMonad.ListMonad.ret /ModelMonad.ListMonad.ret_component /=.
Perhaps you can import locally the required modules in order to refer to shorter names.

2021-04-22 08:18 UTC, eupp commented on relations.v
> +Lemma mem_alt (x : T) (s1 s2 : M T) :
`mem_alt_in` ?

2021-04-22 08:18 UTC, eupp commented on relations.v
> +Qed.
I think it would be better to move this and previous lemma into `monad.v`

2021-04-22 08:18 UTC, eupp commented on relations.v
> +Ltac list_altP := rewrite /Alt /= /monae_lib.curry /= mem_cat.
Why `Ltac`?

2021-04-22 08:18 UTC, eupp commented on relations.v
> +Definition id_nattrans : ModelNondet.list ~> ModelNondet.list :=
Let's move it to `monad.v`. 
Besides that, could we make it a canonical instance somehow?
So that we would be able to infer it automatically instead of passing explicitly. 
@anton-trunov

2021-04-28 16:20 UTC, dmitromikh commented on monad.v
> +Notation "f ≈≈> g" := (monmorph f g) (at level 51) : monae_scope.
OK

2021-04-28 16:20 UTC, dmitromikh commented on relations.v
> +  s >>= (fun a => if p a then Ret a else Fail).
OK

2021-04-28 16:21 UTC, dmitromikh commented on relations.v
> +Lemma mem_ret_eq (x y : T) :
Yeah, it's better

2021-04-28 16:22 UTC, dmitromikh commented on relations.v
> +Lemma mem_alt (x : T) (s1 s2 : M T) :
OK

2021-04-28 16:22 UTC, dmitromikh commented on relations.v
> +Qed.
OK

2021-04-28 16:23 UTC, dmitromikh commented on relations.v
> +Ltac list_altP := rewrite /Alt /= /monae_lib.curry /= mem_cat.
Ah, actually, that is unnecessary, I'll remove it

2021-05-03 12:03 UTC, eupp commented
I've made minor changes. 
In the end, I've left names `mem_ret`/`mem_alt` etc for `\in` lemmas about monads. 
I've also rearranged lemmas a bit so that logically connected lemmas are kept together.

2021-05-03 12:04 UTC, eupp approved these changes

2021-05-03 16:58 UTC, merged